#!/bin/bash
rm -rf /tmp/flircam/*

PIGPIOBIND=$(netstat | grep -P "\b8888\b")
if [ "$PIGPIOBIND" != "" ]; then
    echo $PIGPIOBIND
    exit -1
fi

pigpiod -s 10
if [ $? -ne 0 ]; then
    echo Not starting
    exit -1
fi

# hdmi off
tvservice -o

# bluetooth off
rfkill block 1

# wifi off with rfkill only
# These other commands are not necessary
#  
#   /sbin/ifconfig wlan0 down
#   /sbin/iwconfig wlan0 txpower off

#rfkill block 0

roslaunch flircam flircam.launch &
