#!/bin/bash

# hdmi off
tvservice -o

# bluetooth off
rfkill block 1

# wifi off with rfkill only
# These other commands are not necessary
#  
#   /sbin/ifconfig wlan0 down
#   /sbin/iwconfig wlan0 txpower off

#rfkill block 0

